---
abstract: 'Generate text documentation from Rinci function metadata'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.001, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perinci-Sub-To-Text
requires:
  Data::Dump::OneLine: 0
  Data::Sah: 0.15
  List::MoreUtils: 0
  Locale::Maketext::Lexicon: 0
  Locale::Maketext::Lexicon::Gettext: 0
  Log::Any: 0
  Moo: 0
  Perinci::Object: 0.11
  Rinci: v1.1.35
  SHARYANTO::Role::Doc::Section: 0
  SHARYANTO::Role::Doc::Section::AddTextLines: 0
  SHARYANTO::Role::I18N: 0.15
  SHARYANTO::Role::I18NRinci: 0
  perl: 5.010001
resources: {}
version: 0.28
